### ISSUE TITLE
Access denied even though in ip range

### ISSUE THREAD

**Issue by adamivangrgic** [smerschjohann/mtlswhitelist#1]
Hi, I followed your guide on how to set up the plugin and it seems I cant get it to work.

Here is the relevant config:

traefik.yaml
```
experimental:
  plugins:
    mtlswhitelist:
      moduleName: "github.com/smerschjohann/mtlswhitelist"
      version: "v0.1.0"
```

dynamic.yaml
```
http:
  serversTransports:
    backendTransport:
      insecureSkipVerify: true
  middlewares:
    crowdsec-bouncer:
      ...
    authentik:
      ...
    mtlswhitelist:
      plugin:
        mtlswhitelist:
          rules:
            - type: ipRange
              ipRanges:
                - "192.168.1.0/24"
                - "10.0.8.0/24"
                - "127.0.0.0/8"
    ip-whitelist:
      ...
tls:
  options:
    clientca:
      clientAuth:
        caFiles:
          - /var/traefik/certs/mtls/ca.pem
        clientAuthType: VerifyClientCertIfGiven
```

and as i use docker labels:
```
...
- traefik.http.routers.<name>.middlewares=mtlswhitelist@file,authentik@file
- traefik.http.routers.<name>.tls.options=clientca@file
```

Here are the scenarios:
 - outside ip range & no cert =  denied
 - outside ip range & cert = allowed
 - within ip range & no cert = denied
 - within ip range & cert = allowed

So it looks like the ip whitelist has no effect on whether access is denied or not.
